### ISSUE TITLE
icon stolen

### ISSUE THREAD

**Issue by FuckNico** [developer-lfierrro743/Project-EaglercraftY-1.9-version#44]
You didn't even ask him [[TeckyMan10892](https://www.reddit.com/user/TeckyMan10892/)] if you could use the image:
![image](https://user-images.githubusercontent.com/83834491/234679158-47fd22fe-ae59-4c3e-8c67-aae8b3b28774.png)

**Comment by developer-lfierrro743** [comment]
Uh (i going wait for the I get Approved it to use the Image)

**Comment by developer-lfierrro743** [comment]
It going take time days or Something

**Comment by developer-lfierrro743** [comment]
to respond

**Comment by developer-lfierrro743** [comment]
(i going use AI chat-gpt 4 to Make a discription for  the Game)

**Comment by developer-lfierrro743** [comment]
You going to get Fried!

**Comment by unspeakfan** [comment]
can you include the elytra, potion-tipped arrows, and lingering potions in your new update? thanks

**Comment by developer-lfierrro743** [comment]
I have access Bing Ai
(windows10 edge brower)

**Comment by FailedCoder23** [comment]
idgaf

**Comment by FuckNico** [comment]
suck my cock

**Comment by AR-DEV-1** [comment]
https://github.com/AR-DEV-1/Okicraft
